config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  devise_for :users

  resources :employees
  resources :branches

  get 'admin_panel', to: 'admin_panel#index'
  post 'check' => 'attendances#check'
  get 'reports', to: 'reports#index'

  post 'employees/status/:id', to: 'employees#update_status', as: 'update_status'

  get 'attendances_by_day_pdf', to: 'reports#attendances_by_day_pdf'
  get 'average_checks_by_month_pdf', to: 'reports#average_checks_by_month_pdf'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/models/branch.rb
# == Schema Information
#
# Table name: branches
#
#  id         :bigint           not null, primary key
#  name       :string
#  address    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Branch < ApplicationRecord
  has_many :users
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  include AuthenticateAdmin
  before_action :authenticate_admin!
  before_action :set_branch, only: %i[show edit update destroy]

  def index
    per_page ||= 8
    @pagy, @branches = pagy(Branch.all, items: per_page)
  end

  def show; end

  def new
    @branch = Branch.new
  end

  def edit; end

  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to branches_path, notice: 'Branch was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to branches_path, notice: 'Branch was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
    end
  end

  private

  def set_branch
    @branch = Branch.find(params[:id])
  end

  def branch_params
    params.require(:branch).permit(:name, :address)
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_branch.html.erb
<div id="<%= dom_id branch %>">
  <p>
    <strong>Name:</strong>
    <%= branch.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= branch.address %>
  </p>

</div>

app/views/branches/_form.html.erb
<div class='col-10 mx-auto py-2 py-lg-3 mb-5 mb-md-0'>
  <div class='card'>
    <div class='card-header'>
      <%= header_label %>
    </div>
    <div class='card-body'>
      <%= form_with(model: branch) do |f| %>
        <div class='mb-3'>
          <%= f.label :name, class: 'form-label' %>
          <%= f.text_field :name, placeholder: 'Enter name', class: 'form-control' %>
          <% branch.errors.full_messages_for(:name).each do |message| %>
            <div class='form-text text-danger'>
              <%= message %>
            </div>
          <% end %>
        </div>

        <div class='mb-3'>
          <%= f.label :address, class: 'form-label' %>
          <%= f.text_field :address, placeholder: 'Enter address', class: 'form-control' %>
          <% branch.errors.full_messages_for(:address).each do |message| %>
            <div class='form-text text-danger'>
              <%= message %>
            </div>
          <% end %>
        </div>

        <div class='row gx-2 justify-content-end'>
          <div class='col-auto'>
            <%= f.submit button_label, class: 'btn btn-primary' %>
          </div>
          <div class='col-auto'>
            <%= link_to 'Cancel', branches_path, class: 'btn btn-danger' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/branches/edit.html.erb
<%= render 'form', 
    branch: @branch, 
    header_label: 'Edit company', 
    button_label: 'Edit company' %>

app/views/branches/index.html.erb
<div class='col-xl-10 mx-auto'>
  <h1>Companies</h1>
  <p>
    <%= link_to "New company", new_branch_path, class:"btn btn-primary" %>
  </p>

  <div class='table-responsive-lx'>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Address</th>
          <th scope="col">Created at</th>
          <th scope="col">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @branches.each do |branch| %>
          <tr>
            <th scope="row">
              <%= branch.id %>
            </th>
            <td>
              <%= branch.name %>
            </td>
            <td>
              <%= branch.address %>
            </td>
            <td>
              <%= branch.created_at.localtime %>
            </td>
            <td>
              <%= link_to "Edit", edit_branch_path(branch), class: "btn btn-sm btn-outline-secondary" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="d-flex justify-content-center align-items-center mt-5">
    <%= pagy_bootstrap_nav(@pagy).html_safe %>
  </div>
</div>

app/views/branches/new.html.erb
<%= render 'form',
    branch: @branch,
    header_label: 'New company',
    button_label: 'Create company' %>

app/views/branches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @branch %>

<div>
  <%= link_to "Edit this branch", edit_branch_path(@branch) %> |
  <%= link_to "Back to branches", branches_path %>

  <%= button_to "Destroy this branch", @branch, method: :delete %>
</div>