config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  devise_for :users

  resources :employees
  resources :branches

  get 'admin_panel', to: 'admin_panel#index'
  post 'check' => 'attendances#check'
  get 'reports', to: 'reports#index'

  post 'employees/status/:id', to: 'employees#update_status', as: 'update_status'

  get 'attendances_by_day_pdf', to: 'reports#attendances_by_day_pdf'
  get 'average_checks_by_month_pdf', to: 'reports#average_checks_by_month_pdf'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[employee admin]

  validates :name, :email, :private_number, :position, presence: true
  validates :email, uniqueness: { case_sensitive: false },
                    format: { with: URI::MailTo::EMAIL_REGEXP }

  validates :private_number, uniqueness: { case_sensitive: false },
                             format: { with: /\A\d+\z/, message: 'Private number can only have digits.' }

  validates :name, length: { minimum: 5 }
  validates :position, length: { minimum: 3 }
  validates :password, confirmation: { case_sensitive: true }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  include AuthenticateAdmin
  before_action :authenticate_admin!
  before_action :set_employee, only: %i[show edit update update_status]
  before_action :set_branches, only: %i[new edit create update]

  def index
    per_page ||= 8
    @pagy, @employees = pagy(User.all.order(:id), items: per_page)
  end

  def new
    @employee = User.new
  end

  def create
    @employee = User.create employee_params
    if @employee.save
      redirect_to employees_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @employee.update employee_params
      redirect_to employees_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def update_status
    @employee.update(active: !@employee.active)
    redirect_to employees_path
  end

  private

  def set_employee
    @employee = User.find(params[:id])
  end

  def set_branches
    @branches = Branch.all
  end

  def employee_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :position,
      :private_number,
      :active,
      :branch_id
    )
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def status_label(current_status)
    current_status ? 'Deactivate' : 'Activate'
  end

  def button_status(current_status)
    current_status ? 'btn-outline-danger' : 'btn-outline-success'
  end
end

app/views/employees/_form.html.erb
<div class="col-10 mx-auto py-lg-3 mb-5 mb-md-0 py-2">
  <div class="card">
    <div class="card-header">
      <%= header_label %>
    </div>
    <div class="card-body">
      <%= form_with(model: employee, url: url, method: method) do |f| %>

        <div class='mb-3'>
          <%= f.label 'Name', for: 'user_name', class: 'form-label' %>
          <%= f.text_field :name, placeholder: 'Enter name', class: 'form-control' %>
          <% employee.errors.full_messages_for(:name).each do |message| %>
            <div class='form-text text-danger'>
              <%= message %>
            </div>
          <% end %>
        </div>

        <div class='mb-3'>
          <%= f.label 'Email', for: 'user_email', class: 'form-label' %>
          <%= f.text_field :email, placeholder: 'Enter email', class: 'form-control' %>
          <% employee.errors.full_messages_for(:email).each do |message| %>
            <div class='form-text text-danger'>
              <%= message %>
            </div>
          <% end %>
        </div>

        <div class='mb-3'>
          <%= f.label 'Password', for: 'user_password', class: 'form-label' %>
          <%= f.password_field :password, placeholder: 'Enter password', class: 'form-control' %>
          <% employee.errors.full_messages_for(:password).each do |message| %>
            <div class='form-text text-danger'>
              <%= message %>
            </div>
          <% end %>
        </div>

        <div class='mb-3'>
          <%= f.label 'Position', for: 'user_position', class: 'form-label' %>
          <%= f.text_field :position, placeholder: 'Enter position', class: 'form-control' %>
          <% employee.errors.full_messages_for(:position).each do |message| %>
            <div class='form-text text-danger'>
              <%= message %>
            </div>
          <% end %>
        </div>

        <div class='mb-3'>
          <%= f.label 'Private number', for: 'user_private_number', class: 'form-label' %>
          <%= f.text_field :private_number, placeholder: 'Enter private number', class: 'form-control' %>
          <% employee.errors.full_messages_for(:private_number).each do |message| %>
            <div class='form-text text-danger'>
              <%= message %>
            </div>
          <% end %>
        </div>

        <div class='mb-3'>
          <%= f.label 'Company branch', class: 'form-label' %>
          <%= f.select :branch_id, @branches.map { |branch| [branch.name, branch.id] }, {}, {class: 'form-select'} %>
        </div>

        <% if current_page?(edit_employee_path(employee.id || 0)) %>
          <div class='form-check form-switch'>
            <%= f.label 'Active', class: 'form-check-label', for: 'user_active' %>
            <%= f.check_box :active, class: 'form-check-input' %>
          </div>
        <% end %>

        <div class='row gx-2 justify-content-end'>
          <div class="col-auto">
            <%= f.submit button_label, class: 'btn btn-primary' %>
          </div>
          <div class="col-auto">
            <%= link_to 'Cancel', employees_path, class: 'btn btn-danger' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<%= render 'form',
      employee: @employee,
      url: employee_path(@employee),
      method: :patch,
      header_label: 'Edit employee',
      button_label: 'Edit employee' %>

app/views/employees/index.html.erb
<div class='col-xl-10 mx-auto'>
  <h1>Employees</h1>
  <p>
    <%= link_to "New employee", new_employee_path, class: "btn btn-primary" %>
  </p>

  <div class='table-responsive-lx'>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Position</th>
          <th scope="col">Role</th>
          <th scope="col">Company</th>
          <th scope="col">Status</th>
          <th scope="col">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @employees.each do |employee| %>
          <tr>
            <th scope="row">
              <%= employee.id %>
            </th>
            <td>
              <%= employee.name %>
            </td>
            <td>
              <%= employee.email %>
            </td>
            <td>
              <%= employee.position %>
            </td>
            <td>
              <%= employee.role %>
            </td>
            <td>
              <%= employee.branch.name %>
            </td>
            <td class='text-center'>
              <%= button_to status_label(employee.active),
                  update_status_path(employee),
                  method: :post,
                  class: "btn btn-sm #{button_status(employee.active)}" %>
            </td>
            <td>
              <%= link_to "Show", employee_path(employee), class: "btn btn-sm btn-outline-primary" %>

              <%= link_to "Edit", edit_employee_path(employee), class: "btn btn-sm btn-outline-secondary" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="d-flex justify-content-center align-items-center mt-5">
    <%= pagy_bootstrap_nav(@pagy).html_safe %>
  </div>
</div>

app/views/employees/new.html.erb
<%= render 'form',
      employee: @employee,
      url: employees_path,
      method: :post,
      header_label: 'New employee',
      button_label: 'Create employee' %>

app/views/employees/show.html.erb
<div class='col-xl-10 mx-auto'>
  <h1>Employee info</h1>
  <br>
  <div class="card text-center">
    <div class="card-header fw-bold ">
      Employee name:
      <%= @employee.name %>
    </div>
    <div class="card-body">
      <h5 class="card-title lh-lg">
        <strong>Employee ID:</strong>
        <%= @employee.id %></h5>
      <p class="card-text">
        <strong>Email:</strong>
        <%= @employee.email %>
      </p>
      <p class="card-text">
        <strong>Position:</strong>
        <%= @employee.position %>
      </p>
      <p class="card-text">
        <strong>Role:</strong>
        <%= @employee.role %>
      </p>
      <p class="card-text">
        <strong>Branch ID:</strong>
        <%= @employee.branch_id %>
      </p>
      <p class="card-text">
        <strong>Private Number:</strong>
        <%= @employee.private_number %>
      </p>
      <p class="card-text">
        <strong>Status:</strong>
        <span class="badge <%= @employee.active ? 'bg-success' : 'bg-danger' %>">
          <%= @employee.active ? 'active' : 'deactivated' %>
        </span>
      </p>
      <%= link_to 'Edit', edit_employee_path(@employee.id), class:"btn btn-sm btn-outline-primary" %>
    </div>
    <div class="card-footer text-muted">
      Created at:
      <%= @employee.created_at.localtime %>
    </div>
  </div>
</div>