config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  devise_for :users

  resources :employees
  resources :branches

  get 'admin_panel', to: 'admin_panel#index'
  post 'check' => 'attendances#check'
  get 'reports', to: 'reports#index'

  post 'employees/status/:id', to: 'employees#update_status', as: 'update_status'

  get 'attendances_by_day_pdf', to: 'reports#attendances_by_day_pdf'
  get 'average_checks_by_month_pdf', to: 'reports#average_checks_by_month_pdf'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include AuthenticateAdmin
  include AttendencesHelper
  before_action :authenticate_admin!

  def index
    per_page ||= 20
    @pagy, @daily_attendances = pagy(
      Attendance.where(created_at: Date.today.all_day),
      items: per_page
    )
  end

  def attendances_by_day_pdf
    @date_day = Date.today
    @date_day = Date.parse(params[:date_day]) if params[:date_day].present?

    @attendances = Attendance.where(created_at: @date_day.all_day)

    respond_to do |format|
      format.pdf do
        render pdf: "attendace_of_#{@date_day}",
               template: 'reports/attendances_by_day',
               formats: [:html]
      end
    end
  end

  def average_checks_by_month_pdf
    @date_month = current_month
    @date_month = params[:date_month] if params[:date_month].present?
    @average_checks_by_month = AverageChecksByMonth.where(month: @date_month)

    respond_to do |format|
      format.pdf do
        render pdf: "attendace_of_#{@date_month}",
               template: 'reports/average_checks_by_month',
               formats: [:html]
      end
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/attendances_by_day.html.erb
<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" %>

<h1>
  Attendances of
  <%= @date_day %>
</h1>
<table class="table text-center mt-5">
  <thead>
    <tr>
      <th scope="col">Employee name</th>
      <th scope="col">Email</th>
      <th scope="col">Private number</th>
      <th scope="col">Company</th>
      <th scope="col">Check in</th>
      <th scope="col">Check out</th>
    </tr>
  </thead>
  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.user.name %></td>
        <td><%= attendance.user.email %></td>
        <td><%= attendance.user.private_number %></td>
        <td><%= attendance.user.branch.name %></td>
        <td><%= attendance.check_in.localtime %></td>
        <td><%= attendance.check_out.localtime %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/average_checks_by_month.html.erb
<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" %>

<h1>
  Average check in / check out of month
  <%= @date_month %>
</h1>
<table class='table text-center mt-5'>
  <thead>
    <tr>
      <th scope="col">Employee name</th>
      <th scope="col">Company</th>
      <th scope="col">Avg. check in</th>
      <th scope="col"># check ins</th>
      <th scope="col">Avg. check out</th>
      <th scope="col"># check outs</th>
    </tr>
  </thead>
  <tbody>
    <% @average_checks_by_month.each do |avg_check| %>
      <tr>
        <td>
          <%= avg_check.user.name %>
        </td>
        <td>
          <%= avg_check.user.branch.name %>
        </td>
        <td>
          <%= avg_check.avg_check_in.localtime %>
        </td>
        <td>
          <%= avg_check.n_check_ins %>
        </td>
        <td>
          <%= avg_check.avg_check_out.localtime %>
        </td>
        <td>
          <%= avg_check.n_check_outs %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/index.html.erb
<div class='col-xl-10 mx-auto'>
  <h2>Attendances by day</h2>
  <%= form_with url: attendances_by_day_pdf_path(format: :pdf), method: :get do |form| %>
    <%= form.label 'Attendances of', class: 'form-label' %>
    <%= form.date_field :date_day %>
    <%= form.submit 'Download pdf', class: 'btn btn-sm btn-outline-primary', :formtarget => "_blank" %>
  <% end %>

  <hr>

  <h2>Average check in / check out by month</h2>
  <%= form_with url: average_checks_by_month_pdf_path(format: :pdf), method: :get do |form| %>
    <%= form.label 'Average check in / check out of', class: 'form-label' %>
    <%= form.month_field :date_month %>
    <%= form.submit 'Download pdf', class: 'btn btn-sm btn-outline-primary', :formtarget => "_blank" %>
  <% end %>

  <hr>

  <h2>Daily Attendences</h2>
  <div class='table-responsive-lx'>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col"># Employee</th>
          <th scope="col">Employee name</th>
          <th scope="col">Company</th>
          <th scope="col">Check in</th>
          <th scope="col">Check out</th>
        </tr>
      </thead>

      <tbody>
        <% @daily_attendances.each do |attendance| %>
          <tr>
            <td><%= attendance.user_id %></td>
            <td><%= attendance.user.name %></td>
            <td><%= attendance.user.branch.name %></td>
            <td><%= attendance.check_in.localtime %></td>
            <td>
              <% if attendance.check_out %>
                <%= attendance.check_out.localtime %>
              <% else %>
                ---
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="d-flex justify-content-center align-items-center mt-5">
    <%= pagy_bootstrap_nav(@pagy).html_safe %>
  </div>

</div>