config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  devise_for :users

  resources :employees
  resources :branches

  get 'admin_panel', to: 'admin_panel#index'
  post 'check' => 'attendances#check'
  get 'reports', to: 'reports#index'

  post 'employees/status/:id', to: 'employees#update_status', as: 'update_status'

  get 'attendances_by_day_pdf', to: 'reports#attendances_by_day_pdf'
  get 'average_checks_by_month_pdf', to: 'reports#average_checks_by_month_pdf'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/views/layouts/_sidebar.html.erb
<% if signed_in_user_admin? && !is_root_page? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" id='mobile-navbar'>
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <%= current_user.name %>
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <hr>
        <ul class="nav nav-pills flex-column me-auto mb-2 mb-lg-0">
          <li class="nav-item p-2">
            <%= link_to employees_path,
                class: "nav-link link-dark #{current_path?(employees_path)}" do %>
              Employees
            <% end %>
          </li>
          <li class='nav-item p-2'>
            <%= link_to branches_path,
                class: "nav-link link-dark #{current_path?(branches_path)}" do %>
              Companies
            <% end %>
          </li>
          <li class='nav-item p-2'>
            <%= link_to reports_path,
                class: "nav-link link-dark #{current_path?(reports_path)}" do %>
              Reports
            <% end %>
          </li>
        </ul>
        <hr>
        <%= render 'shared/sign_out_button', additional_classes: 'w-100' %>
      </div>
    </div>
  </nav>

  <nav
    class="
      col-md-4
      col-lg-3
      col-xl-2
      d-flex
      flex-column
      flex-shrink-0
      p-3
      bg-light
      h-100
    "
    id='desktop-navbar'
  >
    <div class="d-flex align-items-center mb-3 mb-md-0 me-md-auto">
      <span class="fs-4">
        <%= current_user.name %>
      </span>
    </div>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <%= link_to employees_path,
            class: "nav-link link-dark #{current_path?(employees_path)}" do %>
          Employees
        <% end %>
      </li>
      <li>
        <%= link_to branches_path,
            class: "nav-link link-dark #{current_path?(branches_path)}" do %>
          Companies
        <% end %>
      </li>
      <li>
        <%= link_to reports_path,
            class: "nav-link link-dark #{current_path?(reports_path)}" do %>
          Reports
        <% end %>
      </li>
    </ul>
    <hr>
    <%= link_to 'Dashboard', root_path , class: 'btn btn-primary w-100 my-3' %>
    <%= render 'shared/sign_out_button', additional_classes: 'w-100' %>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reloj Checador</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <div class="container-fluid h-100">
        <div class="row h-100">
          <%= render 'layouts/sidebar' %>
          <div class='col overflow-auto h-100'>
            <% if notice %>
              <div class="alert alert-success">
                <%= notice %>
              </div>
            <% end %>
            <% if alert %>
              <div class="alert alert-warning">
                <%= alert %>
              </div>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>